name: CD

on:
  push:
    branches: [ master, main ]
    
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-supabase-migrations:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Supabase CLI
      run: npm install --global supabase@latest
      
    - name: Login to Supabase
      run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
    - name: Link to Supabase project
      run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      
    - name: Deploy migrations
      run: supabase db push
      
    - name: Run post-deployment scripts
      run: |
        cd supabase/scripts
        for script in *.sql; do
          [ -f "$script" ] || continue
          supabase db execute --file "$script"
        done
